# Generated by Django 5.0.2 on 2024-03-24 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_fb_url_profile_insta_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fb_url',
            new_name='facebook_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='insta_url',
            new_name='instagram_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='linkedin_url',
            new_name='linkedIn_url',
        ),
    ]
